"""Initial migration

Revision ID: b890540e3c52
Revises: 
Create Date: 2025-12-07 19:28:22.997902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b890540e3c52'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_name', sa.String(length=100), nullable=False),
    sa.Column('base_name', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('enchantment_level', sa.SmallInteger(), nullable=False),
    sa.Column('effective_tier', sa.SmallInteger(), sa.Computed('tier + enchantment_level', persisted=True), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_name')
    )
    op.create_index('idx_items_high_tier', 'items', ['base_name', 'tier', 'enchantment_level'], unique=False, postgresql_where=sa.text('tier >= 4'))
    op.create_index('idx_items_lookup', 'items', ['base_name', 'tier', 'enchantment_level'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('api_name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name')
    )
    op.create_table('market_history',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('quality_level', sa.SmallInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('item_count', sa.BigInteger(), nullable=False),
    sa.Column('average_price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'location_id', 'quality_level', 'timestamp')
    )
    op.create_index('idx_history_item_time', 'market_history', ['item_id', 'location_id', 'timestamp'], unique=False)
    op.create_table('market_prices',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('quality_level', sa.SmallInteger(), nullable=False),
    sa.Column('sell_price_min', sa.BigInteger(), nullable=True),
    sa.Column('sell_price_min_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sell_price_max', sa.BigInteger(), nullable=True),
    sa.Column('sell_price_max_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buy_price_min', sa.BigInteger(), nullable=True),
    sa.Column('buy_price_min_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('buy_price_max', sa.BigInteger(), nullable=True),
    sa.Column('buy_price_max_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'location_id', 'quality_level')
    )
    op.create_table('tracked_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracked_items')
    op.drop_table('market_prices')
    op.drop_index('idx_history_item_time', table_name='market_history')
    op.drop_table('market_history')
    op.drop_table('locations')
    op.drop_index('idx_items_lookup', table_name='items')
    op.drop_index('idx_items_high_tier', table_name='items', postgresql_where=sa.text('tier >= 4'))
    op.drop_table('items')
    # ### end Alembic commands ###